### ISSUE TITLE
Action: to add to set is in working group view disabled

### ISSUE THREAD

**Issue by lmataz** [hello-world-20180222/hello-world#1]
Bug was indicated by LM

**Comment by lmezzy** [comment]
Tudetsche, di jagbo du. Ngandso di schema dünnt la mit da go re.

**Comment by lmataz** [comment]
@lmezzy schtimmt, de chöi mer nächscht wuche z de bearbeite plus die nächschte schritt besprächä

**Comment by lmataz** [comment]
no z file zum aluege: 

![bank_house1](https://user-images.githubusercontent.com/36727078/36538442-c8ee40ec-17d3-11e8-8b59-a0f50b240b35.png)

**Comment by lmezzy** [comment]
Bug was reported by qwertz

![bug to add to set in working group view](https://user-images.githubusercontent.com/29139407/36662173-d1f02fe0-1add-11e8-9517-b18231f64a82.gif)
